apiVersion: v1
kind: Service
metadata:
  name: vote
  labels: 
    role: vote
spec:
  selector:
    role: vote
    release: bluegreen
    code: blue 
  ports:
     - port: 80
       targetPort: 80
       nodePort: 30000
  type: NodePort     
