apiVersion: v1
kind: Pod
metadata: 
   name: db
   labels:
     app: postgres
     role: database
spec:
   containers:
      - name: db
        image: postgres
        ports:
          - containerPort: 5432
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
   volumes:
     - name: db-data
       hostPath:
         path: /var/lib/pgdata
         type: DirectoryOrCreate    
